//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int ItemID { get; set; }
        public int PickUpPointID { get; set; }
        public int Size { get; set; }
        public int Quantity { get; set; }
    
        public virtual Sho Sho { get; set; }
        public virtual Shirt Shirt { get; set; }
        public virtual Trouser Trouser { get; set; }
        public virtual PickUpPoint PickUpPoint { get; set; }
        public virtual User User { get; set; }
    }
}
