//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStore.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
	using WebStore.Models;

	public partial class WebStoreDBEntities : DbContext
    {
		public DbSet<PickUpPoint> PickUpPoints { get; set; }
		public DbSet<User> Users { get; set; }
		public DbSet<Order> Orders { get; set; }
		public DbSet<Shirt> Shirts { get; set; }
		public DbSet<Pants> Pants { get; set; }
		public DbSet<Shoes> Shoes { get; set; }

		public WebStoreDBEntities()
			: base("DefaultConnection")
		{
			Database.SetInitializer<WebStoreContext>(null);
		}
	}
}
